import { Rubik } from 'next/font/google';

import Footer from '@/components/Footer/footer';
import Header from '@/components/Header/header';
import { APP_NAME } from '@/lib/config';

import '@/styles/globals.css';

const rubik = Rubik({
  subsets: ['latin'],
  variable: '--font-rubik',
});

export const metadata = {
  title: APP_NAME,
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={rubik.variable}>
      <body className={`grainy ${rubik.variable}`}>
        <Header />
        <div className="mt-[56px] flex-1 px-8">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
